name: Check cabal files

on:
  pull_request: # Required for workflows to be able to be approved from forks
  merge_group:

jobs:
  check-cabal-files:
    runs-on: ubuntu-latest

    steps:
    - name: Install Haskell
      uses: input-output-hk/actions/haskell@latest
      id: setup-haskell
      with:
        cabal-version: "3.10.2.0"

    - uses: actions/checkout@v3

    - name: Cabal check
      run: ./scripts/ci/check-cabal-files.sh
